import { ProblemSolution } from './types';

export const problemSolutions: ProblemSolution[] = [
  {
    id: 'anxiety',
    problem: 'Anxiety & Overthinking',
    icon: '🌊',
    description: 'Ancient techniques to quiet a restless mind.',
    traditionContext: 'In the Bhagavad Gita (Ch 6, Verse 34), Arjuna tells Krishna: "The mind is restless, turbulent, and obstinate." Krishna replies that through practice (abhyasa) and detachment (vairagya), the mind can be steadied. Patanjali\'s Yoga Sutras (1.2) state: "Yoga chitta vritti nirodha" — yoga is the calming of the mind\'s fluctuations. Anxiety is not a flaw; it is the mind\'s natural restlessness that can be trained.',
    practice: 'Nadi Shodhana + Shanti Mantra',
    practiceSteps: [
      'Sit comfortably. Close your eyes.',
      'Close right nostril with thumb. Inhale left (count 4).',
      'Close left nostril with ring finger. Exhale right (count 6).',
      'Inhale right (count 4). Close right.',
      'Exhale left (count 6). One cycle complete.',
      'Repeat for 7-10 cycles.',
      'Chant "Om Shanti Shanti Shanti" 3 times.',
      'Sit in silence for 2 minutes. Notice the shift.',
    ],
    youtubeQuery: 'nadi shodhana pranayama anxiety relief alternate nostril breathing guided',
  },
  {
    id: 'grief',
    problem: 'Grief & Loss',
    icon: '🕊️',
    description: 'When you\'ve lost someone irreplaceable.',
    traditionContext: 'Krishna teaches Arjuna (Gita Ch 2, Verse 22): "As a person sheds worn-out garments and wears new ones, the soul sheds worn-out bodies and enters new ones." The tradition doesn\'t ask you to "get over" grief — it offers a larger frame. The Atman (soul) is eternal. Grief is the mind\'s attachment, not the soul\'s reality.',
    practice: 'Light a Diya + Gita Ch 2 Reading',
    practiceSteps: [
      'At sunset, light a diya in a quiet space.',
      'Sit before the flame. Hands in chin mudra.',
      'Read Gita Chapter 2 (verses 11-30) — the soul never dies.',
      'Offer water to the departed. Say their name silently.',
      'Sit with the flame for 10 minutes. Tears are welcome.',
      'Chant "Om Purnamadah Purnamidam" — the wholeness mantra.',
      'Practice daily for 21 days during acute grief.',
    ],
    youtubeQuery: 'bhagavad gita chapter 2 explained soul never dies grief comfort',
  },
  {
    id: 'sleep',
    problem: 'Sleep Issues',
    icon: '🌙',
    description: 'When you lie awake despite being exhausted.',
    traditionContext: 'Yogic tradition sees sleep issues as Vata imbalance and rajasic (overactive) mind. The Gita (Ch 14) recommends sattvic (calm) practices before bed. Yoga Nidra is a 5,000-year-old technique for deep rest. Hanuman Chalisa before bed is a tradition millions follow for peaceful sleep.',
    practice: 'Yoga Nidra + Hanuman Chalisa',
    practiceSteps: [
      '1 hour before bed, put away screens.',
      'Lie in Shavasana (flat on back, arms at sides).',
      'Listen to guided Yoga Nidra (15-30 min).',
      'Sit up. Chant or play Hanuman Chalisa once.',
      'Lie back down. Chant "Om Namah Shivaya" 9 times.',
      'Focus only on breath.',
      'If thoughts come, return to breath. This is the practice.',
    ],
    youtubeQuery: 'yoga nidra sleep guided hanuman chalisa before bed peaceful',
  },
  {
    id: 'focus',
    problem: 'Lack of Focus',
    icon: '🎯',
    description: 'When you can\'t concentrate on what matters.',
    traditionContext: 'Gita Ch 6, Verse 26: "Wherever this restless mind wanders, bring it back and focus it on the Self." Patanjali\'s Yoga Sutras describe Dharana (concentration) as the 6th limb of yoga. Trataka (candle gazing) is the traditional technique for training focus.',
    practice: 'Trataka (Candle Gazing)',
    practiceSteps: [
      'Place a candle at eye level, arm\'s length away.',
      'Gaze at the flame without blinking.',
      'When eyes tire, close them. Visualize the flame at the third eye.',
      'When the image fades, open eyes and gaze again.',
      'Do this for 10-15 minutes.',
      'Read Gita Ch 6, Verses 25-26 afterwards.',
      'Practice daily. Focus improves within 2 weeks.',
    ],
    youtubeQuery: 'trataka meditation candle gazing concentration focus technique guided',
  },
  {
    id: 'anger',
    problem: 'Anger & Frustration',
    icon: '🔥',
    description: 'When anger gets the better of you.',
    traditionContext: 'Gita Ch 2, Verse 63: "From anger comes delusion, from delusion comes loss of memory, from loss of memory comes destruction." Anger is born of unfulfilled desire. The prescription is not suppression — it is substitution. Shift awareness to breath and chant a cooling mantra.',
    practice: 'Sitali Pranayama + Shiva Mantra',
    practiceSteps: [
      'When anger rises, stop. Step away.',
      'Roll tongue into a tube (or purse lips).',
      'Inhale slowly through the tongue (air feels cool).',
      'Close mouth. Exhale through nose.',
      'Repeat 10-15 breaths.',
      'Chant "Om Namah Shivaya" 21 times silently.',
      'Ask: "What am I really angry about?"',
    ],
    youtubeQuery: 'sitali pranayama cooling breath anger management shiva mantra',
  },
  {
    id: 'loneliness',
    problem: 'Loneliness',
    icon: '🌑',
    description: 'When you feel truly alone.',
    traditionContext: 'The Upanishads teach that loneliness comes from forgetting the Atman (your true self) is one with Brahman (the infinite). Gita Ch 6, Verse 29: "One who sees the Self in all beings sees the same everywhere." Bhakti saints like Meera Bai channeled loneliness into the most beautiful devotional poetry.',
    practice: 'Bhakti Singing + Self-Inquiry',
    practiceSteps: [
      'Play a Krishna bhajan or Hanuman Chalisa.',
      'Sing along — even quietly. Voice bridges isolation and connection.',
      'Sit quietly for 5 minutes after.',
      'Ask gently: "Am I truly alone? Who is aware of this loneliness?"',
      'Don\'t answer with words. Just feel the awareness.',
      'That awareness has never been lonely.',
    ],
    youtubeQuery: 'krishna bhajan devotional singing loneliness meera bhaiji bhajan',
  },
];
