import { ProblemSolution } from './types';

export const problemSolutions: ProblemSolution[] = [
  {
    id: 'anxiety',
    problem: 'Anxiety & Overthinking',
    problemHindi: 'चिंता और अधिक सोचना',
    icon: '🌊',
    description: "When your mind won't stop, these ancient techniques help you find stillness.",
    traditionContext: 'In the Bhagavad Gita (Ch 6, Verse 34), Arjuna asks Krishna: "The mind is restless, turbulent, powerful, and obstinate." Krishna replies that through practice (abhyasa) and detachment (vairagya), the mind can be steadied. Patanjali\'s Yoga Sutras (1.2) state: "Yoga chitta vritti nirodha" — yoga is the calming of the fluctuations of the mind. The tradition teaches that anxiety is not a flaw; it is the mind\'s natural restlessness that can be trained, like a muscle.',
    practice: 'Nadi Shodhana (Alternate Nostril Breathing) + Shanti Mantra',
    practiceSteps: [
      'Sit comfortably with spine straight. Close your eyes.',
      'Place your right thumb on your right nostril. Gently close it.',
      'Inhale deeply through the left nostril (count to 4).',
      'Close the left nostril with your ring finger. Release the right.',
      'Exhale slowly through the right nostril (count to 6).',
      'Inhale through the right nostril (count to 4), close it.',
      'Exhale through the left nostril (count to 6). This is one cycle.',
      'Repeat for 7-10 cycles.',
      'Afterwards, silently chant: "Om Shanti Shanti Shanti" 3 times, feeling peace in mind, body, and spirit.',
      'Sit in silence for 2 minutes. Notice the difference in your mental state.',
    ],
    youtubeQuery: 'nadi shodhana pranayama anxiety relief alternate nostril breathing guided',
  },
  {
    id: 'grief',
    problem: 'Grief & Loss',
    problemHindi: 'शोक और हानि',
    icon: '🕊️',
    description: 'When you have lost someone or something irreplaceable.',
    traditionContext: 'Krishna\'s teaching to Arjuna in the Gita (Ch 2, Verse 22): "As a person sheds worn-out garments and wears new ones, the soul sheds worn-out bodies and enters new ones." The tradition does not ask you to "get over" grief — it offers a larger frame of understanding. The Gita teaches that the Atman (soul) is eternal and cannot be destroyed. Grief is the mind\'s attachment, not the soul\'s reality. Practices like tarpan, lighting a diya for the departed, and reading the Gita\'s teachings on the eternal self provide genuine comfort.',
    practice: 'Lighting a Diya + Gita Ch 2 Reading + Tarpan',
    practiceSteps: [
      'At sunset, light a diya (clay lamp with ghee or oil) in a quiet space.',
      'Sit before the flame. Place hands folded in chin mudra (thumb and index finger touching).',
      'Read or listen to Bhagavad Gita Chapter 2 (verses 11-30) — Krishna\'s teaching that the soul never dies.',
      'Offer a small cup of water to the departed, silently speaking their name. Say: "May you find peace wherever you are."',
      'Sit with the flame for 10 minutes. Let yourself feel. Tears are welcome.',
      'Chant: "Om Purnamadah Purnamidam..." (the peace mantra from Brihadaranyaka Upanishad that speaks of wholeness beyond loss).',
      'This practice can be done daily for 21 days during acute grief.',
    ],
    youtubeQuery: 'bhagavad gita chapter 2 explained soul never dies grief comfort',
  },
  {
    id: 'sleep',
    problem: 'Sleep Issues',
    problemHindi: 'नींद न आना',
    icon: '🌙',
    description: 'When you lie awake despite being exhausted.',
    traditionContext: 'Yogic tradition recognizes sleep disturbances as a sign of Vata imbalance (movement energy gone wild) and rajasic (overactive) mind. The Gita (Ch 14) discusses the three gunas — and recommends sattvic (pure, calm) practices before bed. Yoga Nidra ("yogic sleep") is a 5,000-year-old technique specifically for deep rest and sleep issues. Hanuman Chalisa before bed is a traditional practice millions of Indians swear by for peaceful sleep.',
    practice: 'Yoga Nidra + Hanuman Chalisa (Bedtime Version)',
    practiceSteps: [
      '1 hour before bed, put away phone and screens.',
      'Lie down in Shavasana (flat on back, arms at sides, palms up).',
      'Listen to a guided Yoga Nidra for sleep (video below). This takes 15-30 minutes.',
      'After Yoga Nidra, sit up and chant or play Hanuman Chalisa once quietly.',
      'Lie back down. Chant "Om Namah Shivaya" 9 times slowly.',
      'Focus only on your breath. Nothing else.',
      'If thoughts come, gently return to breath. This is the practice.',
      'You will naturally fall asleep during this process.',
    ],
    youtubeQuery: 'yoga nidra sleep guided hanuman chalisa before bed peaceful',
  },
  {
    id: 'focus',
    problem: 'Lack of Focus',
    problemHindi: 'ध्यान नहीं लगना',
    icon: '🎯',
    description: "When you can't concentrate on work, study, or anything important.",
    traditionContext: 'Gita Ch 6, Verse 26: "Yato yato niscalati manas cancalam asthiram. Tatas tato niyamyaitad atmany eva vasam nayet" — "Wherever this restless, unsteady mind wanders, bring it back and focus it on the Self." Patanjali\'s Yoga Sutras describe Dharana (concentration) as the 6th limb of yoga — the practice of binding awareness to a single point. Trataka (gazing meditation) is the traditional yogic technique for training focus.',
    practice: 'Trataka (Candle Gazing) + Gita Ch 6 Mind Discipline',
    practiceSteps: [
      "Place a candle at eye level, arm's length away.",
      'Sit comfortably. Light the candle.',
      'Gaze at the flame without blinking for as long as comfortable.',
      "When eyes tire, close them and visualize the flame at the third eye point (between eyebrows).",
      'When the image fades, open eyes and gaze again.',
      'Do this for 10-15 minutes.',
      'Afterwards, read Gita Chapter 6, Verses 25-26 (about controlling the mind).',
      'Practice this daily. Focus will noticeably improve within 2 weeks.',
    ],
    youtubeQuery: 'trataka meditation candle gazing concentration focus technique guided',
  },
  {
    id: 'anger',
    problem: 'Anger & Frustration',
    problemHindi: 'क्रोध और निराशा',
    icon: '🔥',
    description: 'When anger gets the better of you and you regret it later.',
    traditionContext: 'Gita Ch 2, Verse 63: "Krodhad bhavati sammohah sammohat smriti-vibhramah" — "From anger comes delusion, from delusion comes loss of memory, from loss of memory comes destruction of intelligence." The tradition teaches that anger is born of unfulfilled desire (kama) and attachment to outcomes. The prescription is not suppression — it is substitution. When anger arises, shift awareness to breath and chant a cooling mantra. Shiva is the transformer of anger into awareness.',
    practice: 'Sitali Pranayama (Cooling Breath) + Shiva Mantra',
    practiceSteps: [
      'When you feel anger rising, stop. Step away if possible.',
      "Roll your tongue into a tube (if you can't, purse your lips instead).",
      'Inhale slowly and deeply through the rolled tongue (the air will feel cool).',
      'Close mouth. Exhale slowly through the nose.',
      'Repeat 10-15 breaths. The coolness physically calms the nervous system.',
      'Now chant silently: "Om Namah Shivaya" 21 times.',
      'When the chant is done, ask yourself: "What am I really angry about?" The answer is rarely what triggered it.',
      'This practice rewires the anger response over time.',
    ],
    youtubeQuery: 'sitali pranayama cooling breath anger management shiva mantra',
  },
  {
    id: 'loneliness',
    problem: 'Loneliness',
    problemHindi: 'अकेलापन',
    icon: '🌑',
    description: 'When you feel no one truly understands or is with you.',
    traditionContext: 'The Upanishads teach that the deepest loneliness comes from forgetting that the Atman (your true self) is never alone — it is one with Brahman (the infinite). Gita Ch 6, Verse 29: "One who sees the Self in all beings, and all beings in the Self, sees the same everywhere." Devotion practices reframe loneliness as the longing of the soul for the divine — this is actually a spiritual blessing in disguise. Bhakti saints like Meera Bai and Tulsidas channeled loneliness into the most beautiful devotional poetry India has produced.',
    practice: 'Bhakti (Devotional Singing) + Self-Inquiry',
    practiceSteps: [
      'Put on a Krishna bhajan or Hanuman chalisa video (below).',
      'Sing along — even if quietly. The voice is a bridge between isolation and connection.',
      'After singing, sit quietly for 5 minutes.',
      'Ask yourself gently: "Am I truly alone? Who is aware of this loneliness?"',
      "Don't answer with words. Just feel the awareness that is always present.",
      'That awareness has never been lonely.',
      'This practice, done daily, transforms loneliness from burden into spiritual fuel.',
    ],
    youtubeQuery: 'krishna bhajan devotional singing loneliness meera bhaiji bhajan',
  },
];
